export default {
  REQUEST_OPEN_CREATE_NEW_NOTE_DIALOG: "REQUEST_OPEN_CREATE_NEW_NOTE_DIALOG",
  RESPONSE_OPEN_CREATE_NEW_NOTE_DIALOG: "RESPONSE_OPEN_CREATE_NEW_NOTE_DIALOG",
  REQUEST_CLOSE_CREATE_NEW_NOTE_DIALOG: "REQUEST_OPEN_CREATE_NEW_NOTE_DIALOG",
  RESPONSE_CLOSE_CREATE_NEW_NOTE_DIALOG: "RESPONSE_OPEN_CREATE_NEW_NOTE_DIALOG"
};
