export default {
  // CREATE NOTE DIALOG
  REQUEST_OPEN_CREATE_NEW_NOTE_DIALOG: "REQUEST_OPEN_CREATE_NEW_NOTE_DIALOG",
  RESPONSE_OPEN_CREATE_NEW_NOTE_DIALOG: "RESPONSE_OPEN_CREATE_NEW_NOTE_DIALOG",
  REQUEST_CLOSE_CREATE_NEW_NOTE_DIALOG: "REQUEST_CLOSE_CREATE_NEW_NOTE_DIALOG",
  RESPONSE_CLOSE_CREATE_NEW_NOTE_DIALOG: "RESPONSE_CLOSE_CREATE_NEW_NOTE_DIALOG",

  // REMOVE NOTE DIALOG
  REQUEST_OPEN_REMOVE_NOTE_DIALOG: "REQUEST_OPEN_REMOVE_NOTE_DIALOG",
  RESPONSE_OPEN_REMOVE_NOTE_DIALOG: "RESPONSE_OPEN_REMOVE_NOTE_DIALOG",
  REQUEST_CLOSE_REMOVE_NOTE_DIALOG: "REQUEST_CLOSE_REMOVE_NOTE_DIALOG",
  RESPONSE_CLOSE_REMOVE_NOTE_DIALOG: "RESPONSE_CLOSE_REMOVE_NOTE_DIALOG",

  // EXPORT NOTE DIALOG
  REQUEST_OPEN_EXPORT_NOTE_DIALOG: "REQUEST_OPEN_EXPORT_NOTE_DIALOG",
  RESPONSE_OPEN_EXPORT_NOTE_DIALOG: "RESPONSE_OPEN_EXPORT_NOTE_DIALOG",
  REQUEST_CLOSE_EXPORT_NOTE_DIALOG: "REQUEST_CLOSE_EXPORT_NOTE_DIALOG",
  RESPONSE_CLOSE_EXPORT_NOTE_DIALOG: "RESPONSE_CLOSE_EXPORT_NOTE_DIALOG",

  // IMPORT NOTE DIALOG
  REQUEST_OPEN_IMPORT_NOTE_DIALOG: "REQUEST_OPEN_IMPORT_NOTE_DIALOG",
  RESPONSE_OPEN_IMPORT_NOTE_DIALOG: "RESPONSE_OPEN_IMPORT_NOTE_DIALOG",
  REQUEST_CLOSE_IMPORT_NOTE_DIALOG: "REQUEST_CLOSE_IMPORT_NOTE_DIALOG",
  RESPONSE_CLOSE_IMPORT_NOTE_DIALOG: "RESPONSE_CLOSE_IMPORT_NOTE_DIALOG",

  // REPLACE NOTE CONFIGURATION DIALOG
  REQUEST_OPEN_NOTE_CONFIG_DIALOG: "REQUEST_OPEN_NOTE_CONFIG_DIALOG",
  RESPONSE_OPEN_NOTE_CONFIG_DIALOG: "RESPONSE_OPEN_NOTE_CONFIG_DIALOG",
  REQUEST_CLOSE_NOTE_CONFIG_DIALOG: "REQUEST_CLOSE_NOTE_CONFIG_DIALOG",
  RESPONSE_CLOSE_NOTE_CONFIG_DIALOG: "RESPONSE_CLOSE_NOTE_CONFIG_DIALOG",

  // SET QUESTION OF SAVE NOTE DIALOG WHEN LEAVE PAGE
  REQUEST_SET_MISSING_SAVE_NOTE: "REQUEST_SET_MISSING_SAVE_NOTE",
  RESPONSE_SET_MISSING_SAVE_NOTE: "RESPONSE_SET_MISSING_SAVE_NOTE"
};
