export default {
  // New NOte
  REQUEST_NEW_NOTE: "REQUEST_NEW_NOTE",
  RESPONSE_NEW_NOTE: "RESPONSE_NEW_NOTE",
  // Save Note
  REQUEST_SAVE_NOTE: "REQUEST_SAVE_NOTE",
  RESPONSE_SAVE_NOTE: "RESPONSE_SAVE_NOTE",
  // Load Note
  REQUEST_LOAD_NOTE: "REQUEST_LOAD_NOTE",
  RESPONSE_LOAD_NOTE: "RESPONSE_LOAD_NOTE",
  // Remove Note
  REQUEST_REMOVE_NOTE: "REQUEST_REMOVE_NOTE",
  RESPONSE_REMOVE_NOTE: "RESPONSE_REMOVE_NOTE",
  // Move to note page
  REQUEST_MOVE_TO_NOTE_PAGE: "REQUEST_MOVE_TO_NOTE_PAGE",
  RESPONSE_MOVE_TO_NOTE_PAGE: "RESPONSE_MOVE_TO_NOTE_PAGE",
  // UNSET Current note on store
  REQUEST_UNSET_CURRENT_NOTE: "REQUEST_UNSET_CURRENT_NOTE",
  RESPONSE_UNSET_CURRENT_NOTE: "RESPONSE_UNSET_CURRENT_NOTE",
  // SUGGEST SAVE NOTE BUTTON ON SERVICE NAV
  REQUEST_SUGGEST_SAVE_NOTE: "REQUEST_SUGGEST_SAVE_NOTE",
  RESPOSE_SUGGEST_SAVE_NOTE: "RESPOSE_SUGGEST_SAVE_NOTE"
};
