export default {
  // New NOte
  REQUEST_NEW_NOTE: "REQUEST_NEW_NOTE",
  RESPONSE_NEW_NOTE: "RESPONSE_NEW_NOTE",
  // Save Note
  REQUEST_SAVE_NOTE: "REQUEST_SAVE_NOTE",
  RESPONSE_SAVE_NOTE: "RESPONSE_SAVE_NOTE",
  // Load Note
  REQUEST_LOAD_NOTE: "REQUEST_LOAD_NOTE",
  RESPONSE_LOAD_NOTE: "RESPONSE_LOAD_NOTE",
  // Remove Note
  REQUEST_REMOVE_NOTE: "REQUEST_REMOVE_NOTE",
  RESPONSE_REMOVE_NOTE: "RESPONSE_REMOVE_NOTE",
  // NOTE LIST
  REQUEST_NOTE_LIST: "REQUEST_NOTE_LIST",
  RESPONSE_NOTE_LIST: "RESPONSE_NOTE_LIST",
  // Move to note page
  REQUEST_MOVE_TO_NOTE_PAGE: "REQUEST_MOVE_TO_NOTE_PAGE",
  RESPONSE_MOVE_TO_NOTE_PAGE: "RESPONSE_MOVE_TO_NOTE_PAGE",
  // UNSET Current note on store
  REQUEST_UNSET_CURRENT_NOTE: "REQUEST_UNSET_CURRENT_NOTE",
  RESPONSE_UNSET_CURRENT_NOTE: "RESPONSE_UNSET_CURRENT_NOTE",
  // SUGGEST SAVE NOTE BUTTON ON SERVICE NAV
  REQUEST_SUGGEST_SAVE_NOTE: "REQUEST_SUGGEST_SAVE_NOTE",
  RESPONSE_SUGGEST_SAVE_NOTE: "RESPONSE_SUGGEST_SAVE_NOTE",
  // EXPORT NOTE
  REQUEST_EXPORT_NOTE: "REQUEST_EXPORT_NOTE",
  RESPONSE_EXPORT_NOTE: "RESPONSE_EXPORT_NOTE",
  CLEAR_EXPORT_NOTE: "CLEAR_EXPORT_NOTE",
  // IMPORT NOTE
  REQUEST_IMPORT_NOTE: "REQUEST_IMPORT_NOTE",
  RESPONSE_IMPORT_NOTE: "RESPONSE_IMPORT_NOTE",
  // Execute note
  REQUEST_EXECUTE_CODE_CONTAINER: "REQUEST_EXECUTE_CODE_CONTAINER",
  RESPONSE_EXECUTE_CODE_CONTAINER: "RESPONSE_EXECUTE_CODE_CONTAINER",
};
